name: seg
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-version=12.8=h30beaf8_3
  - expat=2.7.1=h6a678d5_0
  - faiss-gpu=1.9.0=py3.10_ha2e4562_0_cuda12.1.1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.8.4.1=hbdd6827_1
  - libfaiss=1.9.0=h4818125_0_cuda12.1.1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.30=h46f56fc_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - annoy==1.17.3
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - bs4==0.0.2
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.3.0
      - dill==0.4.0
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.27.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.6.1
      - outcome==1.3.0.post0
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.2
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - pysqlite3==0.5.4
      - python-crfsuite==0.9.11
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvi==0.1.1
      - pyyaml==6.0.3
      - rank-bm25==0.2.2
      - regex==2025.9.18
      - requests==2.32.5
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - selenium==4.36.0
      - sentence-transformers==5.1.2
      - six==1.17.0
      - sklearn-crfsuite==0.5.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - torch-rechub==0.0.3
      - tqdm==4.67.1
      - transformers==4.57.1
      - trio==0.31.0
      - trio-websocket==0.12.2
      - triton==3.5.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unidecode==1.4.0
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uv==0.9.7
      - websocket-client==1.9.0
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/minh/miniconda3/envs/Web
